version: "3.8"
services:
    kedro:
      build: .
      ports:
        - "8888:8888"
      volumes:
        - ./:/kedro/home/
        - kedro_packages:/kedro/.local/
      container_name: kedro
volumes:
    kedro_packages: